# Generated by Django 5.2.5 on 2025-09-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Local')),
            ],
            options={
                'verbose_name': 'Destino de Entrega',
                'verbose_name_plural': 'Destinos de Entrega',
            },
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.destinoentrega', verbose_name='Destino de Entrega'),
        ),
    ]
