# Generated by Django 5.2.5 on 2025-09-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_destinoentrega_solicitacaocompra_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assinatura_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/', verbose_name='Imagem da Assinatura'),
        ),
    ]
