# Generated by Django 5.2.5 on 2025-09-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_user_assinatura_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisicaomaterial',
            old_name='data_assinatura_engenheiro',
            new_name='data_assinatura_diretor',
        ),
        migrations.RemoveField(
            model_name='requisicaomaterial',
            name='assinatura_engenheiro',
        ),
        migrations.AddField(
            model_name='requisicaomaterial',
            name='assinatura_diretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rms_assinadas_diretor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicaomaterial',
            name='status_assinatura',
            field=models.CharField(choices=[('pendente', 'Pendente de Assinaturas'), ('aguardando_diretor', 'Aguardando Diretor'), ('assinada', 'Assinada'), ('enviada', 'Enviada para Fornecedor')], default='pendente', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('almoxarife_obra', 'Almoxarife da Obra'), ('engenheiro', 'Engenheiro'), ('almoxarife_escritorio', 'Almoxarife do Escritório'), ('diretor', 'Diretor')], max_length=30),
        ),
    ]
