# Generated by Django 5.2.5 on 2025-09-06 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_rename_data_assinatura_engenheiro_requisicaomaterial_data_assinatura_diretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='endereco_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.destinoentrega', verbose_name='Endereço de Entrega'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Frete'),
        ),
        migrations.AddField(
            model_name='enviocotacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('avista', 'À Vista'), ('pix', 'Pix'), ('boleto', 'Boleto Bancário'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('transferencia', 'Transferência Bancária'), ('a_negociar', 'A Negociar')], default='a_negociar', max_length=20, verbose_name='Forma de Pagamento Sugerida'),
        ),
        migrations.AddField(
            model_name='enviocotacao',
            name='prazo_pagamento',
            field=models.PositiveIntegerField(default=0, help_text='Prazo de pagamento sugerido ao fornecedor em dias.', verbose_name='Prazo de Pagamento (dias)'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente_aprovacao', 'Pendente de Aprovação'), ('aprovado_engenharia', 'Aprovado - Engenharia'), ('aprovada', 'Cotação - Para Iniciar'), ('rejeitada', 'Rejeitada'), ('em_cotacao', 'Cotação - Em Andamento'), ('aguardando_resposta', 'Cotação - Aguardando Resposta'), ('cotacao_selecionada', 'Cotação - Recebida/Analisar'), ('finalizada', 'RM Gerada'), ('a_caminho', 'A Caminho'), ('recebida', 'Recebida')], default='rascunho', max_length=20),
        ),
    ]
