# Generated by Django 5.2.5 on 2025-09-06 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0005_cotacao_endereco_entrega_cotacao_valor_frete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('nota_fiscal', models.FileField(upload_to='recebimentos/notas_fiscais/', verbose_name='Nota Fiscal')),
                ('sc_assinada', models.FileField(upload_to='recebimentos/scs_assinadas/', verbose_name='SC Assinada')),
                ('boleto_comprovante', models.FileField(upload_to='recebimentos/comprovantes/', verbose_name='Boleto/Comprovante')),
                ('recebedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Recebedor')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='materiais.solicitacaocompra', verbose_name='Solicitação de Compra')),
            ],
            options={
                'verbose_name': 'Recebimento',
                'verbose_name_plural': 'Recebimentos',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Recebida')),
                ('item_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='materiais.itemsolicitacao')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_recebidos', to='materiais.recebimento')),
            ],
            options={
                'verbose_name': 'Item Recebido',
                'verbose_name_plural': 'Itens Recebidos',
            },
        ),
    ]
