# Generated by Django 5.2.5 on 2025-09-15 03:09

import materiais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0006_recebimento_itemrecebido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecebido',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='boleto_comprovante',
            field=models.FileField(upload_to=materiais.models.get_recebimento_upload_path, verbose_name='Boleto/Comprovante'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='nota_fiscal',
            field=models.FileField(upload_to=materiais.models.get_recebimento_upload_path, verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='sc_assinada',
            field=models.FileField(upload_to=materiais.models.get_recebimento_upload_path, verbose_name='SC Assinada'),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente_aprovacao', 'Pendente de Aprovação'), ('aprovado_engenharia', 'Aprovado - Engenharia'), ('aprovada', 'Cotação - Para Iniciar'), ('rejeitada', 'Rejeitada'), ('em_cotacao', 'Cotação - Em Andamento'), ('aguardando_resposta', 'Cotação - Aguardando Resposta'), ('cotacao_selecionada', 'Cotação - Recebida/Analisar'), ('finalizada', 'RM Gerada'), ('a_caminho', 'A Caminho'), ('recebida_parcial', 'Recebida Parcialmente'), ('recebida', 'Recebida')], default='rascunho', max_length=20),
        ),
    ]
