# Generated by Django 5.2.5 on 2025-09-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0008_alter_recebimento_boleto_comprovante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrecebido',
            name='item_solicitado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='materiais.itemsolicitacao'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='materiais.solicitacaocompra', verbose_name='Solicitação de Compra'),
        ),
    ]
