# Generated by Django 5.2.5 on 2025-09-18 16:18

import django.db.models.deletion
import materiais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0009_alter_itemrecebido_item_solicitado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaocompra',
            options={},
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='boleto_comprovante',
            field=models.FileField(blank=True, null=True, upload_to=materiais.models.get_boleto_comprovante_upload_path, verbose_name='Boleto/Comprovante'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='nota_fiscal',
            field=models.FileField(blank=True, null=True, upload_to=materiais.models.get_nota_fiscal_upload_path, verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='sc_assinada',
            field=models.FileField(blank=True, null=True, upload_to=materiais.models.get_sc_assinada_upload_path, verbose_name='SC Assinada'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='materiais.solicitacaocompra', verbose_name='Solicitação de Compra'),
        ),
    ]
