# Generated by Django 5.2.3 on 2025-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0010_alter_solicitacaocompra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcatalogo',
            name='is_agregado',
            field=models.BooleanField(default=False, verbose_name='É Agregado?'),
        ),
    ]
