# Generated by Django 5.2.5 on 2025-10-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0011_itemcatalogo_is_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaitem',
            name='embedding',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
