# Generated by Django 5.2.5 on 2025-10-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0012_categoriaitem_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaomaterial',
            name='header_choice',
            field=models.CharField(choices=[('A', 'RM - Construtora Boa Vista Ltda'), ('B', 'RM - FR. Incorporações e Construções LTDA.')], default='A', max_length=1, verbose_name='Cabeçalho da RM'),
        ),
    ]
